config/routes.rb
App::Application.routes.draw do
  get 'products' => 'products#index'

  controller :sessions do
    get '/finalize' => :finalize
    get '/login' => :new
    post '/login' => :create
    delete '/logout' => :destroy
  end
  root :to => 'products#index'

  

end

app/models/product.rb
class Product

  def self.to_xml entries
    check_connection
    return if entries.length < 1
    builder = Nokogiri::XML::Builder.new { |xml|
      xml.products {
        entries.each { |entry|
          xml.product {
            xml.aid entry.id
            xml.name entry.title
            xml.desc CGI::escapeHTML(entry.description_html.nil? ? '' : entry.description_html.html_safe)
            xml.price entry.price
            xml.link entry.url
            xml.brand entry.vendor
            xml.shop_cat entry.category
            xml.image entry.featured_image_url
          }
        }
      }  
    }
    builder.to_xml
  end

  private

  def self.check_connection
    VersaConnection.check_connection
  end

end

app/models/versa_connection.rb
module VersaConnection

  TOKEN = 'b21f8f11'
  SITE_URL = 'test-produkte.versacommerce.de'

  @@established=false
  def self.established
    @@established
  end


  def self.establish!
    session  = VersacommerceAPI::Session.new(SITE_URL,TOKEN)
    if session.valid?
      VersacommerceAPI::Base.activate_session(session)
      @@established = true
    else
      @@established = false
      raise 'NotValidSession'
    end

  end

  def self.established?
    @@established
  end
  
  def self.check_connection
    VersaConnection.establish! unless VersaConnection.established?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_locale

  private

  def extract_locale_from_accept_language_header
    browser_locale   = request.env['HTTP_ACCEPT_LANGUAGE'].try(:scan, /^[a-z]{2}/).try(:first).try(:to_sym)
    session[:locale] = browser_locale if I18n.available_locales.include? browser_locale
  end

  def set_locale
    extract_locale_from_accept_language_header if session[:locale].blank?
    session[:locale] = I18n.default_locale if session[:locale].blank?
    session[:locale] = params[:locale] if params[:locale]
    I18n.locale = session[:locale]
    Rails.application.routes.default_url_options[:locale]= I18n.locale 
  end

end

app/controllers/home_controller.rb
# -*- encoding : utf-8 -*-
class HomeController < ApplicationController
  around_filter :ensure_current_api_session
    
  def index
    # get 10 products
    @products = VersacommerceAPI::Product.find(:all, :params => {:limit => 10})

    # get latest 5 orders
    @orders   = VersacommerceAPI::Order.find(:all, :params => {:limit => 5, :order => "created_at DESC" })
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  respond_to :xml, :html

  before_action :check_connection

  def index
    @products = VersacommerceAPI::Product.all
    respond_to do |format|
      format.xml { render :xml => Product.to_xml(@products) }
      format.html
    end
  end

  private

  def check_connection
    VersaConnection.check_connection
  end

end

app/controllers/sessions_controller.rb
# -*- encoding : utf-8 -*-
class SessionsController < ApplicationController

  def new
    authenticate if params[:shop].present?
  end

  def create
    authenticate
  end
    
  def destroy
    session[:versacommerce] = nil
    flash[:success]         = t('sessions.controller.destroy')
    redirect_to :action => 'new'
  end
  
  def finalize
    current_session = VersacommerceAPI::Session.new(params[:shop], params[:t], params)
    if current_session.valid?
      #
      # IF YOU WANT TO SAVE THE TOKEN FOR LATER USE,
      #
      # 1) CREATE A MODEL
      # $ rails generate model user shop:string token:string
      # $ rake db:create && rake db:migrate
      #
      # 2) SAVE THE TOKEN RIGHT HERE
      # User.where(shop: params[:shop]).first_or_create do |user|
      #   user.token = params[:t]
      # end
      #
      # 3) USE THE TOKEN TO CONNECT TO THIS SHOP WITHOUT USER INTERACTION
      # https://github.com/versacommerce/versacommerce_api (see sample code)
      #
      session[:versacommerce] = current_session
      flash[:success]         = t('sessions.controller.finalize_ok')
      redirect_to return_address
    else
      flash[:warning] = t('sessions.controller.finalize_error')
      redirect_to :action => 'index'
    end
  end
  
  protected
  
  def authenticate
    if shop_name = sanitize_shop_param(params)
      redirect_to VersacommerceAPI::Session.new(shop_name).create_permission_url
    else
      redirect_to return_address
    end
  end
  
  def return_address
    session[:return_to] || root_url
  end
  
  def sanitize_shop_param(params)
    return unless params[:shop].present?
    name = params[:shop].to_s.strip
    name += '.versacommerce.de' if !name.include?("versacommerce.de") && !name.include?(".")
    name.sub('https://', '').sub('http://', '')
    u = URI("http://#{name}")
    u.host.ends_with?("versacommerce.de") ? u.host : nil
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
# -*- encoding : utf-8 -*-
module HomeHelper

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
# -*- encoding : utf-8 -*-
module SessionsHelper  
  
end

app/views/home/index.html.erb
<div class="page-header">
  <h1>How does this work?</h1>
</div>
<p class="lead">
  This is the VersaCommerce App Template build on <a href="http://getbootstrap.com" target="_blank">Bootstrap 3</a>.
  To get the ball rolling: It uses the <a href="https://github.com/versacommerce/versacommerce_api" target="_blank">VersaCommerce API GEM</a> for accessing the VersaCommerce admin REST web services. It is build with the <a href="https://github.com/versacommerce/versacommerce_app" target="_blank">versacommerce_app generator</a> which provides a <a href="https://github.com/versacommerce/versacommerce_app/blob/master/lib/versacommerce_app/ensure_api_session.rb" target="_blank">module</a> to ensure the API-Session.
</p>


<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Check out the code</h3>
  </div>
  <div class="panel-body">
    <p>
      <p><strong>Check out the</strong> <code>home_controller</code></p>
      <p>The controller in this demo application fetches the newest 5 orders and products and makes them available as instance variables <code>@orders</code> and <code>@products</code></p>
    </p>
    <p>
      <p><strong>Take a look at</strong> <code>index.html.erb</code></p>
      <p>Index is the Ruby template you are currently viewing. Have a look at the markup and Ruby code to see how the VersaCommerce API is being used. It's located at <code>views/home/index.html.erb</code></p>
    </p>
    <p>
      <p><strong>Check out the</strong> <code>sessions_controller</code></p>
      <p>The sessions-controller in this demo application makes sure, you are connected to a VersaCommerce Shop. If not, it asks you to register (install) your app with a shop. After authorisation it calls the action <code>sessions#finalize</code>. If you want to store the &quot;registration-token&quot; <code>token</code> for unattended usage, you can place your code right here.</p>
    </p>
  </div>
</div>


<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Additional Documentation</h3>
  </div>
  <div class="panel-body">
    <p>
      <%= link_to 'API documentation', 'https://github.com/versacommerce/vc-api' %><br/>
      <span class="note">Learn what you can do with the VersaCommerce API</span>
    </p>
    <p>
      <%= link_to 'Bootstrap documentation', 'http://twitter.github.com/bootstrap/' %><br/>
      <span class="note">Find out what you can do with Twitter Bootstrap</span>
    </p>
  </div>
</div>


<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">About this Shop</h3>
  </div>
  <div class="panel-body">
    <p>
      <p><strong>Name</strong></p>
      <p><%= current_shop.shop.name %></p>
    </p>
    <p>
      <p><strong>URL</strong></p>
      <p><%= current_shop.shop.url %></p>
    </p>
    <p>
      <p><strong>Price includes tax</strong></p>
      <p><%= current_shop.shop.price_includes_tax%></p>
    </p>
    <p>
      <p><strong>Currency</strong></p>
      <p><%= current_shop.shop.currency_code%></p>
    </p>
  </div>
</div>


<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Recent Orders</h3>
  </div>
  <div class="panel-body">

    <% if @orders.blank? %>
      <table class="table table-striped">
        <tr>
          <td><em>There are no orders in your shop.</em></td>
        </tr>
      </table>
    <% else %>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Order</th>
            <th>Customer</th>
            <th>Status</th>
            <th>Total</th>
          </tr>
        </thead>
      <% @orders.each do |order| %>
        <tr>
          <td><%= link_to order.code, "https://#{current_shop.url}/admin/orders/#{order.id}", :target => 'blank' %></td>
          <td><%= "#{order.billing_address.firstname} #{order.billing_address.lastname}" %></td>
          <td>
            <%= order.status %>
          </td>
          <td><%= order.total %> <%= order.currency %></td>
        </tr>
      <% end %>
      </table>
    <% end %>

  </div>
</div>


<h4>New Products</h4>
  
<% if @products.blank? %>

  <div class="panel-group">
    <div class="panel-heading">
      <em>There are no products in your shop.</em>
    </div>
  </div>

<% else %>

  <div class="accordion" id="accordion">      
    <div class="panel-group">

      <%  @products.each_with_index do |product, index| %>
        <div class="panel panel-default">

          <div class="panel-heading">
            <h4 class="panel-title">
              <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse<%= product.id %>">
                <%= product.title %>
              </a>
              <span class="pull-right muted"><%= product.price %> <%= current_shop.shop.currency_code %></span>
            </h4>
          </div>
  
          <div id="collapse<%= product.id %>" class="panel-body collapse <% if index == 0 %>in<% end %>">
            <div class="panel-body">
              <%= image_tag( product.featured_image.medium, class: "pull-right" ) unless product.featured_image_url.blank? %>                
              <p><strong>SKU:</strong> <%= product.code %></p>
              <p><strong>Category:</strong> <%= product.category %></p>
              <p><strong>Vendor:</strong> <%= product.vendor %></p>
              <%= raw(product.description_html) %>
              <br/>
              <p class="muted">Created at <%= product.created_on.strftime("%Y-%m-%d") %></p>
              <br/>
              <%= link_to "Open this product in /admin", "http://#{current_shop.url}/admin/catalog/products/#{product.id}/edit", :target => 'blank', class: "btn btn-default" %>
            </div>
          </div>

        </div>
      <% end %>

    </div>

  </div>
<% end %>

<br/><br/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../assets/favicon.png">
    <link rel="apple-touch-icon" href="../assets/versacommerce-57.png">
    <link rel="apple-touch-icon" sizes="72x72" href="../assets/versacommerce-72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="../assets/versacommerce-114.png">

    <title>VersaCommerce Sample App</title>

    <!-- Bootstrap core CSS -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">

    <%= stylesheet_link_tag 'application' %>

    <style type="text/css" media="screen">
      /* Sticky footer styles
      -------------------------------------------------- */

      html,
      body {
        height: 100%;
        /* The html and body elements cannot have any padding or margin. */
      }

      /* Wrapper for page content to push down footer */
      #wrap {
        min-height: 100%;
        height: auto !important;
        height: 100%;
        /* Negative indent footer by its height */
        margin: 0 auto -60px;
        /* Pad bottom by footer height */
        padding: 0 0 60px;
      }

      /* Set the fixed height of the footer here */
      #footer {
        height: 60px;
        background-color: #f5f5f5;
      }


      /* Custom page CSS
      -------------------------------------------------- */

      #wrap > .container {
        padding: 60px 15px 0;
      }
      .container .credit {
        margin: 20px 0;
      }

      #footer > .container {
        padding-left: 15px;
        padding-right: 15px;
      }

      code {
        font-size: 80%;
      }
    </style>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
      <!-- <script src="../../assets/js/respond.min.js"></script> -->
    <![endif]-->
    <%= csrf_meta_tags %>
  </head>

  <body>

    <!-- Wrap all page content here -->
    <div id="wrap">
      <!-- Fixed navbar -->
      <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to 'VersaCommerce App', '/', :class => 'navbar-brand' %>
          </div>
          <% if current_shop %>
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li><a href="https://github.com/versacommerce/vc-api" target="_blank">API Documentation</a></li>
              <li><a href="https://github.com/versacommerce/versacommerce_api" target="_blank">API GEM</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_shop.url %> <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to raw('<i class="icon-home"></i> Shop'), "http://"+current_shop.url, :target => 'blank' %></li>
                  <li><%= link_to raw('<i class="icon-cog"></i> Admin'), "http://"+current_shop.url+"/admin", :target => 'blank' %></li>
                  <li class="divider"></li>
                  <li><%= link_to raw('<i class="icon-off"></i> Logout'), logout_path, :method => :delete %></li>
                </ul>
              </li>
            </ul>
          </div><!--/.nav-collapse -->
          <% end %>
        </div>
      </div>

      <!-- Begin page content -->
      <div class="container">
        <% flash.each do |type, message| %>
          <div class="alert alert-<%= type %>"><%= message %></div>
        <% end %>
        <%= yield %>
      </div>
    </div>

    <div id="footer">
      <div class="container">
        <p class="text-muted credit">VersaCommerce Example App. Created by <a href="http://www.versacommerce.de" target="_blank">versacommerce.de</a></p>
      </div>
    </div>

    <%= javascript_include_tag 'application' %>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/products/index.html.haml
=link_to 'XML', products_path(format: :xml)